// ---------------------------------------------------------------------------
// Page automation only. This worker creates/appends standalone Notion pages
// (cron-triggered weekly planning/wrap-up notes, ad hoc page creation via the
// /api/notion-worker proxy). It does NOT sync CRM contacts — that's handled
// by the managed Notion Worker in workers/src/index.ts (backfill + 5-minute
// delta sync against /api/internal/contacts).
// ---------------------------------------------------------------------------

const NOTION_VERSION = '2022-06-28'

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'GET, POST, OPTIONS',
      'access-control-allow-headers': 'content-type',
    },
  })
}

function textBlock(text) {
  return {
    type: 'paragraph',
    paragraph: {
      rich_text: [{ type: 'text', text: { content: String(text || '') } }],
    },
  }
}

function headingBlock(text) {
  return {
    type: 'heading_2',
    heading_2: {
      rich_text: [{ type: 'text', text: { content: String(text || '') } }],
    },
  }
}

// Constant-time string comparison to avoid leaking length/content via timing.
function safeCompare(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string' || a.length !== b.length) return false
  let result = 0
  for (let i = 0; i < a.length; i++) {
    result |= a.charCodeAt(i) ^ b.charCodeAt(i)
  }
  return result === 0
}

function requireWorkerAuth(request, env) {
  if (!env.WORKER_SHARED_SECRET) {
    return json({ ok: false, error: 'Worker secret not configured' }, 401)
  }
  const provided = request.headers.get('x-latimore-worker-secret')
  if (!provided || !safeCompare(provided, env.WORKER_SHARED_SECRET)) {
    return json({ ok: false, error: 'Unauthorized worker request' }, 401)
  }
  return null
}

function buildChildren(sections = []) {
  return sections.flatMap((section) => {
    const blocks = []
    if (section.heading) blocks.push(headingBlock(section.heading))
    if (section.body) blocks.push(textBlock(section.body))
    return blocks
  })
}

async function createNotionPage(env, payload) {
  if (!env.NOTION_TOKEN) {
    return json({ ok: false, error: 'Missing NOTION_TOKEN secret' }, 500)
  }
  if (!env.NOTION_PARENT_PAGE_ID) {
    return json({ ok: false, error: 'Missing NOTION_PARENT_PAGE_ID var' }, 500)
  }

  const title = payload.title || 'Untitled'
  const children = buildChildren(payload.sections)

  const response = await fetch('https://api.notion.com/v1/pages', {
    method: 'POST',
    headers: {
      authorization: `Bearer ${env.NOTION_TOKEN}`,
      'content-type': 'application/json',
      'notion-version': NOTION_VERSION,
    },
    body: JSON.stringify({
      parent: { type: 'page_id', page_id: env.NOTION_PARENT_PAGE_ID },
      properties: {
        title: { title: [{ type: 'text', text: { content: String(title) } }] },
      },
      children,
    }),
  })

  const result = await response.json()
  if (!response.ok) {
    return json({ ok: false, error: 'Notion API request failed', status: response.status, notion: result }, response.status)
  }

  return json({ ok: true, action: 'create_page', page_id: result.id, url: result.url })
}

async function appendNotionPage(env, payload) {
  if (!env.NOTION_TOKEN) {
    return json({ ok: false, error: 'Missing NOTION_TOKEN secret' }, 500)
  }

  const pageId = payload.page_id || payload.pageId || env.NOTION_PARENT_PAGE_ID
  if (!pageId) {
    return json({ ok: false, error: 'Missing page_id' }, 400)
  }

  const children = buildChildren(payload.sections)
  if (!children.length) {
    return json({ ok: false, error: 'Missing sections' }, 400)
  }

  const response = await fetch(`https://api.notion.com/v1/blocks/${pageId}/children`, {
    method: 'PATCH',
    headers: {
      authorization: `Bearer ${env.NOTION_TOKEN}`,
      'content-type': 'application/json',
      'notion-version': NOTION_VERSION,
    },
    body: JSON.stringify({ children }),
  })

  const result = await response.json()
  if (!response.ok) {
    return json({ ok: false, error: 'Notion API request failed', status: response.status, notion: result }, response.status)
  }

  return json({ ok: true, action: 'append_page', page_id: pageId, appended: result.results?.length || 0 })
}

async function handleCron(controller, env) {
  const cron = controller.cron
  const now = new Date(controller.scheduledTime).toISOString()

  if (cron === '0 13 * * 1') {
    return createNotionPage(env, {
      title: `Latimore OS Weekly Planning - ${now.slice(0, 10)}`,
      sections: [
        { heading: 'Purpose', body: 'Weekly planning note generated by Cloudflare Cron Trigger.' },
        { heading: 'Focus', body: 'Review CRM, content, follow-ups, PAHS/community activity, and operating bottlenecks.' },
      ],
    })
  }

  if (cron === '0 13 * * 5') {
    return createNotionPage(env, {
      title: `Latimore OS Weekly Wrap-Up - ${now.slice(0, 10)}`,
      sections: [
        { heading: 'Purpose', body: 'Weekly wrap-up note generated by Cloudflare Cron Trigger.' },
        { heading: 'Review', body: 'Summarize wins, missed follow-ups, content performance, and next-week priorities.' },
      ],
    })
  }

  return createNotionPage(env, {
    title: `Latimore OS Cron Run - ${now.slice(0, 10)}`,
    sections: [
      { heading: 'Cron', body: cron },
      { heading: 'Status', body: 'Cron fired, but no specific route matched.' },
    ],
  })
}

export default {
  async scheduled(controller, env, ctx) {
    ctx.waitUntil(handleCron(controller, env))
  },
  async fetch(request, env) {
    if (request.method === 'OPTIONS') {
      return json({ ok: true })
    }
    if (request.method === 'GET') {
      return json({ ok: true, service: 'latimore-notion-worker', mode: 'notion-api-enabled', actions: ['create_page', 'append_page'] })
    }
    if (request.method !== 'POST') {
      return json({ ok: false, error: 'Method not allowed' }, 405)
    }

    const unauthorized = requireWorkerAuth(request, env)
    if (unauthorized) return unauthorized

    let payload
    try {
      payload = await request.json()
    } catch {
      return json({ ok: false, error: 'Invalid JSON body' }, 400)
    }

    if (payload.action === 'create_page') {
      return createNotionPage(env, payload)
    }
    if (payload.action === 'append_page') {
      return appendNotionPage(env, payload)
    }

    return json({ ok: false, error: 'Unsupported action' }, 400)
  },
}
