-- Supabase RLS is now managed by checked-in Prisma migrations.
--
-- Do not paste ad-hoc RLS SQL as a normal deploy step. Run:
--
--   npm run db:deploy
--   npm run security:rls:check
--
-- The RLS migrations currently include:
-- - prisma/migrations/20260617000000_enable_row_level_security/migration.sql
-- - prisma/migrations/20260622000000_complete_rls_coverage/migration.sql
--
-- This file remains only as an operator note for older deployment guides.
