const NOTION_VERSION = '2022-06-28'

function json(data, status = 200) {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type,x-latimore-worker-secret',
    },
  })
}

function notionHeaders(env) {
  return {
    Authorization: `Bearer ${env.NOTION_TOKEN}`,
    'Notion-Version': NOTION_VERSION,
    'Content-Type': 'application/json',
  }
}

function richText(text, limit = 1900) {
  return [{ type: 'text', text: { content: String(text || '').slice(0, limit) } }]
}

function paragraph(text) {
  return { object: 'block', type: 'paragraph', paragraph: { rich_text: richText(text) } }
}

function heading(text) {
  return { object: 'block', type: 'heading_2', heading_2: { rich_text: richText(text, 100) } }
}

function bullet(text) {
  return { object: 'block', type: 'bulleted_list_item', bulleted_list_item: { rich_text: richText(text) } }
}

function normalizeSections(sections = []) {
  const children = []
  for (const section of Array.isArray(sections) ? sections : []) {
    if (section?.heading) children.push(heading(section.heading))
    if (section?.body) children.push(paragraph(section.body))
    if (Array.isArray(section?.items)) {
      for (const item of section.items) children.push(bullet(item))
    }
  }
  return children
}

async function createPage(env, { title, sections = [] }) {
  const children = normalizeSections(sections)
  const response = await fetch('https://api.notion.com/v1/pages', {
    method: 'POST',
    headers: notionHeaders(env),
    body: JSON.stringify({
      parent: { page_id: env.NOTION_PARENT_PAGE_ID },
      properties: {
        title: {
          title: [{ type: 'text', text: { content: String(title || 'Latimore OS Note').slice(0, 100) } }],
        },
      },
      children: children.length ? children : [paragraph('Created by Latimore OS Notion Worker.')],
    }),
  })
  const data = await response.json().catch(() => ({}))
  return { ok: response.ok, action: 'create_page', status: response.status, data }
}

async function appendToPage(env, { pageId, content, sections = [] }) {
  const children = normalizeSections(sections)
  if (content) children.unshift(paragraph(content))

  const response = await fetch(`https://api.notion.com/v1/blocks/${pageId}/children`, {
    method: 'PATCH',
    headers: notionHeaders(env),
    body: JSON.stringify({ children: children.length ? children : [paragraph('Update from Latimore OS.')] }),
  })
  const data = await response.json().catch(() => ({}))
  return { ok: response.ok, action: 'append_page', status: response.status, data }
}

async function createScheduledReport(env, controller) {
  const label = controller?.cron?.includes('1') ? 'Weekly Planning Check-In' : 'Weekly Wrap Report'
  return createPage(env, {
    title: `Latimore OS — ${label}`,
    sections: [
      { heading: 'Executive Summary', body: 'Automated Latimore OS report generated by Cloudflare Cron.' },
      { heading: 'CRM', body: 'Review stale leads, missed bookings, no-shows, and high-intent contacts.' },
      { heading: 'Marketing', body: 'Review content pipeline, PAHS/Coal Region campaigns, and next conversion assets.' },
      { heading: 'Systems', body: 'Verify GitHub, Vercel, Notion, Supabase, and worker health.' },
    ],
  })
}

function requireWorkerAuth(request, env) {
  if (!env.WORKER_SHARED_SECRET) return json({ ok: false, error: 'Worker secret not configured' }, 401)
  const provided = request.headers.get('x-latimore-worker-secret')
  if (provided !== env.WORKER_SHARED_SECRET) return json({ ok: false, error: 'Unauthorized worker request' }, 401)
  return null
}

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') return json({ ok: true })

    if (request.method !== 'POST') {
      return json({
        ok: true,
        service: 'latimore-notion-worker',
        mode: 'notion-api-enabled',
        actions: ['create_page', 'append_page'],
      })
    }

    const unauthorized = requireWorkerAuth(request, env)
    if (unauthorized) return unauthorized

    if (!env.NOTION_TOKEN) return json({ ok: false, error: 'Missing NOTION_TOKEN secret' }, 500)
    if (!env.NOTION_PARENT_PAGE_ID) return json({ ok: false, error: 'Missing NOTION_PARENT_PAGE_ID' }, 500)

    let body
    try {
      body = await request.json()
    } catch {
      return json({ ok: false, error: 'Invalid JSON' }, 400)
    }

    const action = String(body.action || 'create_page')
    if (action === 'create_page') return json(await createPage(env, body))
    if (action === 'append_page') {
      if (!body.pageId) return json({ ok: false, error: 'Missing pageId' }, 400)
      return json(await appendToPage(env, body))
    }

    return json({ ok: false, error: `Unknown action: ${action}` }, 400)
  },

  async scheduled(controller, env) {
    if (!env.NOTION_TOKEN || !env.NOTION_PARENT_PAGE_ID) return
    await createScheduledReport(env, controller)
  },
}
