import { z } from 'zod'

const stageEnum = z.enum(['New', 'Attempted_Contact', 'Qualified', 'Booked', 'Sold', 'Follow_Up', 'Lost'])
const productEnum = z.enum([
  'Mortgage_Protection',
  'Final_Expense',
  'Term_Life',
  'Whole_Life',
  'Child_Whole_Life',
  'Accident',
  'Critical_Illness',
  'IUL',
  'Annuity',
  'Retirement',
  'Business',
  'General',
])
const eventEnum = z.enum([
  'page_view',
  'cta_click',
  'call_click',
  'text_click',
  'email_click',
  'book_click',
  'form_submit',
  'lead_created',
  'appointment_booked',
  'stage_changed',
  'county_selected',
  'product_selected',
  'lead_magnet_download',
  'post_viewed',
  'post_created',
  'post_published',
  'reaction_added',
  'legacy_checkup_started',
  'legacy_checkup_step_completed',
  'legacy_checkup_completed',
  'lead_submitted',
  'book_consultation_clicked',
  'instant_quote_clicked',
  'service_card_clicked',
  'gbp_service_visit',
])

export const FilloutSchema = z.object({
  email: z.string().email('Invalid email').optional().nullable(),
  first_name: z.string().max(100).optional().nullable(),
  firstName: z.string().max(100).optional().nullable(),
  last_name: z.string().max(100).optional().nullable(),
  lastName: z.string().max(100).optional().nullable(),
  phone: z.string().max(40).optional().nullable(),
  county: z.string().max(100).optional().nullable(),
  product_interest: z.string().max(100).optional().nullable(),
  productInterest: z.string().max(100).optional().nullable(),
  interest_type: z.string().max(100).optional().nullable(),
  interestType: z.string().max(100).optional().nullable(),
  lead_session_id: z.string().max(191).optional().nullable(),
  page_url: z.string().max(500).optional().nullable(),
  landing_page: z.string().max(500).optional().nullable(),
  source: z.string().max(100).optional().nullable(),
  utm_source: z.string().max(100).optional().nullable(),
  utm_medium: z.string().max(100).optional().nullable(),
  utm_campaign: z.string().max(150).optional().nullable(),
  utm_term: z.string().max(100).optional().nullable(),
  utmTerm: z.string().max(100).optional().nullable(),
  utm_content: z.string().max(100).optional().nullable(),
  utmContent: z.string().max(100).optional().nullable(),
  referrer: z.string().max(500).optional().nullable(),
  notes: z.string().max(2000).optional().nullable(),
}).passthrough()

export const EventIngestSchema = z.object({
  eventType: z.string().min(1).max(100),
  occurredAt: z.string().optional().nullable(),
  leadSessionId: z.string().max(191).optional().nullable(),
  contactId: z.string().max(191).optional().nullable(),
  inquiryId: z.string().max(191).optional().nullable(),
  pageUrl: z.string().max(500).optional().nullable(),
  referrer: z.string().max(500).optional().nullable(),
  source: z.string().max(100).optional().nullable(),
  medium: z.string().max(100).optional().nullable(),
  campaign: z.string().max(150).optional().nullable(),
  county: z.string().max(100).optional().nullable(),
  productInterest: z.string().max(100).optional().nullable(),
  metadata: z.record(z.any()).optional().nullable(),
})

export const LeadSchema = z.object({
  firstName: z.string().max(100).optional().nullable(),
  lastName: z.string().max(100).optional().nullable(),
  email: z.string().email().optional().nullable(),
  phone: z.string().max(40).optional().nullable(),
  county: z.string().max(100).optional().nullable(),
  productInterest: z.string().max(100).optional().nullable(),
  leadSessionId: z.string().max(191).optional().nullable(),
  source: z.string().max(100).optional().nullable(),
  medium: z.string().max(100).optional().nullable(),
  campaign: z.string().max(150).optional().nullable(),
  term: z.string().max(100).optional().nullable(),
  content: z.string().max(100).optional().nullable(),
  utmTerm: z.string().max(100).optional().nullable(),
  utmContent: z.string().max(100).optional().nullable(),
  referrer: z.string().max(500).optional().nullable(),
  landingPage: z.string().max(500).optional().nullable(),
  notes: z.string().max(2000).optional().nullable(),
  metadata: z.record(z.any()).optional().nullable(),
}).refine((value) => !!(value.email || value.phone), {
  message: 'Lead must include at least an email or phone number',
  path: ['email'],
})

export const ProductFitSchema = z.object({
  fullName: z.string().min(2).max(150),
  email: z.string().email().max(191).optional().or(z.literal('')),
  phone: z.string().min(7).max(50),
  state: z.string().max(100).optional().nullable(),
  county: z.string().max(100).optional().nullable(),
  lifeStage: z.enum(['young_family', 'pre_retiree', 'retiree', 'business_owner', 'high_income', 'other']).optional().nullable(),
  hasMortgage: z.boolean().optional().nullable(),
  hasDependents: z.boolean().optional().nullable(),
  ownsBusiness: z.boolean().optional().nullable(),
  hasEmployees: z.boolean().optional().nullable(),
  wantsRetirementIncome: z.boolean().optional().nullable(),
  wantsLegacyPlanning: z.boolean().optional().nullable(),
  timeline: z.enum(['now', '30_days', '90_days', 'researching']).optional().nullable(),
  bestContactTime: z.string().max(80).optional().nullable(),
  productInterest: z.string().max(100).optional().nullable(),
  selectedProductSlug: z.string().max(100).optional().nullable(),
  notes: z.string().max(2000).optional().nullable(),
  leadSessionId: z.string().max(191).optional().nullable(),
  pageUrl: z.string().max(500).optional().nullable(),
  referrer: z.string().max(500).optional().nullable(),
  source: z.string().max(100).optional().nullable(),
  medium: z.string().max(100).optional().nullable(),
  campaign: z.string().max(150).optional().nullable(),
  term: z.string().max(100).optional().nullable(),
  content: z.string().max(100).optional().nullable(),
  hp_company: z.string().max(200).optional().nullable(),
})

export const LeadIngestSchema = LeadSchema

export const InquiryPatchSchema = z.object({
  stage: stageEnum,
  notes: z.string().max(2000).optional().nullable(),
  actor: z.string().max(100).optional().nullable(),
  force: z.boolean().optional(),
})

export const BookingNotifySchema = z.object({
  inquiryId: z.string().max(191).optional().nullable(),
  lead_session_id: z.string().min(1).max(191).optional().nullable(),
  gcal_id: z.string().max(200).optional().nullable(),
  scheduled_for: z.string().optional().nullable(),
  start_at: z.string().optional().nullable(),
  end_at: z.string().optional().nullable(),
  booking_source: z.string().max(100).optional().nullable(),
  source: z.string().max(100).optional().nullable(),
  medium: z.string().max(100).optional().nullable(),
  campaign: z.string().max(150).optional().nullable(),
  location: z.string().max(250).optional().nullable(),
  meeting_url: z.string().max(500).optional().nullable(),
  timezone: z.string().max(100).optional().nullable(),
  title: z.string().max(250).optional().nullable(),
  description: z.string().max(2000).optional().nullable(),
  first_name: z.string().max(100).optional().nullable(),
  firstName: z.string().max(100).optional().nullable(),
  last_name: z.string().max(100).optional().nullable(),
  lastName: z.string().max(100).optional().nullable(),
  full_name: z.string().max(150).optional().nullable(),
  fullName: z.string().max(150).optional().nullable(),
  name: z.string().max(150).optional().nullable(),
  email: z.string().email().optional().nullable(),
  attendee_email: z.string().email().optional().nullable(),
  phone: z.string().max(40).optional().nullable(),
  county: z.string().max(100).optional().nullable(),
  product_interest: z.string().max(100).optional().nullable(),
  productInterest: z.string().max(100).optional().nullable(),
  page_url: z.string().max(500).optional().nullable(),
  notes: z.string().max(2000).optional().nullable(),
  metadata: z.record(z.any()).optional().nullable(),
}).refine((value) => !!(value.inquiryId || value.lead_session_id || value.email || value.attendee_email || value.phone), {
  message: 'Booking webhook must include an inquiry/session id or contact email/phone',
  path: ['email'],
})

export const CardEventSchema = z.object({
  event: z.string().min(1).max(100),
  label: z.string().max(200).optional().nullable(),
  pageUrl: z.string().max(500).optional().nullable(),
  referrer: z.string().max(500).optional().nullable(),
  userAgent: z.string().max(300).optional().nullable(),
  timestamp: z.string().optional().nullable(),
  leadSessionId: z.string().max(191).optional().nullable(),
  productInterest: z.string().max(100).optional().nullable(),
  county: z.string().max(100).optional().nullable(),
  metadata: z.record(z.any()).optional().nullable(),
})

export const VirtualIntakeSchema = z.object({
  journey: z.enum(['client', 'business_partner', 'both']),
  firstName: z.string().min(1).max(100),
  lastName: z.string().min(1).max(100),
  email: z.string().email(),
  phone: z.string().max(40).optional().nullable(),
  state: z.string().max(100).optional().nullable(),
  selectedPriorities: z.array(z.string().max(100)).max(10).optional(),
  topPriorityWhy: z.string().max(1000).optional().nullable(),

  maritalStatus: z.string().max(50).optional().nullable(),
  spouseName: z.string().max(150).optional().nullable(),
  ageRange: z.string().max(50).optional().nullable(),
  smoker: z.boolean().optional().nullable(),
  hasChildren: z.boolean().optional().nullable(),
  childrenAges: z.string().max(200).optional().nullable(),
  occupation: z.string().max(150).optional().nullable(),
  familyNotes: z.string().max(2000).optional().nullable(),
  recreationNotes: z.string().max(2000).optional().nullable(),
  motivationNotes: z.string().max(2000).optional().nullable(),

  monthlyIncome: z.number().finite().optional().nullable(),
  monthlyExpenses: z.number().finite().optional().nullable(),
  emergencyFund: z.number().finite().optional().nullable(),
  marketAssets: z.number().finite().optional().nullable(),
  hasEmergencyFund: z.boolean().optional().nullable(),
  emergencyFundMonths: z.number().finite().optional().nullable(),

  hasEmployerRetirement: z.boolean().optional().nullable(),
  retirementPlanTypes: z.array(z.string().max(100)).max(10).optional(),
  retirementBalance: z.number().finite().optional().nullable(),
  retirementContribution: z.number().finite().optional().nullable(),
  contributionFrequency: z.string().max(50).optional().nullable(),
  hasCompanyMatch: z.boolean().optional().nullable(),
  companyMatchDetails: z.string().max(500).optional().nullable(),
  hasOutsideRetirement: z.boolean().optional().nullable(),

  hasLifeInsurance: z.boolean().optional().nullable(),
  lifeInsuranceSource: z.string().max(150).optional().nullable(),
  coverageAmount: z.number().finite().optional().nullable(),
  premiumAmount: z.number().finite().optional().nullable(),
  premiumFrequency: z.string().max(50).optional().nullable(),
  policyType: z.string().max(100).optional().nullable(),
  hasLivingBenefits: z.boolean().optional().nullable(),
  hasLtc: z.boolean().optional().nullable(),

  taxStatus: z.string().max(100).optional().nullable(),
  taxAmount: z.number().finite().optional().nullable(),
  minMonthlySavings: z.number().finite().optional().nullable(),
  maxMonthlySavings: z.number().finite().optional().nullable(),
  savingForChildren: z.boolean().optional().nullable(),
  additionalIncomeInterest: z.boolean().optional().nullable(),

  debt: z.number().finite().optional().nullable(),
  mortgageBalance: z.number().finite().optional().nullable(),
  educationGoal: z.number().finite().optional().nullable(),
})

export { stageEnum as PipelineStageSchema, productEnum as ProductInterestSchema, eventEnum as EventTypeSchema }
