import type { WeeklyReportAnalysis } from './weekly-report'

function pdfEscape(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[^\x20-\x7E]/g, ' ')
    .slice(0, 200)
}

function lines(label: string, items: string[]): string[] {
  const out: string[] = [`${label}:`]
  for (const item of items.slice(0, 8)) {
    out.push(`  - ${item.slice(0, 150)}`)
  }
  return out
}

export function weeklyReportToPdfBuffer(
  analysis: WeeklyReportAnalysis,
  meta: { weekStart: Date; weekEnd: Date; totals: Record<string, number> }
): Buffer {
  const title = `Weekly Report: ${meta.weekStart.toDateString()} – ${meta.weekEnd.toDateString()}`

  const textLines: string[] = [
    title,
    '',
    'Executive Summary:',
    analysis.summary,
    '',
    `KPIs: Impressions ${meta.totals.impressions ?? 0} | Reach ${meta.totals.reach ?? 0} | Clicks ${meta.totals.clicks ?? 0} | Leads ${meta.totals.leads ?? 0}`,
    '',
    ...lines('KPI Highlights', analysis.kpi_highlights),
    '',
    ...lines('Top Performing', analysis.top_performing),
    '',
    ...lines('Growth Opportunities', analysis.growth_opportunities),
    '',
    ...lines('Risks to Watch', analysis.risks),
    '',
    ...lines('Recommended Actions', analysis.recommended_actions),
    '',
    ...lines('Recommended Posts', analysis.recommended_posts),
    '',
    'Generated by Latimore Life & Legacy Hub OS',
  ]

  const pageWidth = 612
  const pageHeight = 792
  const margin = 60
  const lineHeight = 16
  const fontSize = 10
  const titleSize = 14

  let yPos = pageHeight - margin
  const contentParts: string[] = []

  contentParts.push(`BT\n/F1 ${titleSize} Tf\n${margin} ${yPos} Td\n(${pdfEscape(textLines[0])}) Tj\nET\n`)
  yPos -= lineHeight * 2

  for (const line of textLines.slice(1)) {
    if (yPos < margin + lineHeight) {
      yPos = pageHeight - margin
    }
    const size = line.startsWith('  -') ? fontSize - 1 : fontSize
    const weight = /^[A-Z].*:$/.test(line) ? '/F2' : '/F1'
    const display = line.replace(/^ {2}- /, '• ').replace(/^ {2}/, '')
    contentParts.push(`BT\n${weight} ${size} Tf\n${margin} ${yPos} Td\n(${pdfEscape(display)}) Tj\nET\n`)
    yPos -= lineHeight
  }

  const contentStream = contentParts.join('')

  const objects: string[] = []
  const offsets: number[] = []
  let pos = 0

  function addObj(content: string): number {
    const n = objects.length + 1
    offsets.push(pos)
    const obj = `${n} 0 obj\n${content}\nendobj\n`
    objects.push(obj)
    pos += obj.length
    return n
  }

  const catalogId = 1
  const pagesId = 2
  const pageId = 3
  const contentId = 4
  const font1Id = 5
  const font2Id = 6

  const streamBytes = Buffer.from(contentStream, 'latin1')

  const header = '%PDF-1.4\n'
  pos = header.length

  addObj(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`)
  addObj(`<< /Type /Pages /Kids [${pageId} 0 R] /Count 1 >>`)
  addObj(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${contentId} 0 R /Resources << /Font << /F1 ${font1Id} 0 R /F2 ${font2Id} 0 R >> >> >>`)
  addObj(`<< /Length ${streamBytes.length} >>\nstream\n${contentStream}\nendstream`)
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`)
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`)

  const xrefOffset = pos + objects.reduce((a, o) => a + o.length, 0) - objects[objects.length - 1].length + offsets[offsets.length - 1]

  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const off of offsets) {
    xref += String(off + header.length).padStart(10, '0') + ' 00000 n \n'
  }

  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  const parts = [header, ...objects, xref, trailer]
  return Buffer.concat(parts.map(p => Buffer.from(p, 'latin1')))
}
